# Question 1. What will be the output of the following Python code?


In [1]:
def func(a, b=5, c=10):
    return a + b * c

print(func(2, c=3))


17


# Explanation

The function has default parameters:

- b = 5
- c = 10

When the function is called as func(2, c=3):

- a = 2 (given)
- b = 5 (default value)
- c = 3 (overridden)

The calculation becomes:

a + b × c  
= 2 + 5 × 3  
= 2 + 15  
= 17



# Output

17


# Question 2. What is the scope of a variable declared inside a function?


In [2]:
def my_func():
    x = 10   # local variable
    print("Inside function:", x)

my_func()

# print(x)  # This will give an error because x is not accessible outside


Inside function: 10


# Explanation

A variable declared inside a function has **local scope**.

This means:

- It can only be accessed within that function.
- It is created when the function is called.
- It is destroyed when the function execution ends.

Trying to access it outside the function will result in a NameError.


# Question 3. What does the following code return?


In [3]:
def f(x, lst=[]):
    lst.append(x)
    return lst

print(f(1))
print(f(2))


[1]
[1, 2]


# Explanation

In Python, default mutable arguments (like lists) are created only once
when the function is defined, not each time the function is called.

Step-by-step:

1️⃣ First call → f(1)  
- lst is the default empty list []  
- 1 is appended → [1]  

2️⃣ Second call → f(2)  
- The SAME list is used (not a new one)  
- 2 is appended → [1, 2]

This happens because the default list persists across function calls.


# Output

[1]
[1, 2]


# Question 4. Which statement about *args is correct?


In [4]:
def add_numbers(*args):
    return sum(args)

print(add_numbers(1, 2, 3, 4))


10


# Explanation

*args is used in a function definition to allow a variable number of
positional arguments to be passed.

Key points:

- It collects extra positional arguments into a tuple.
- The name "args" is just a convention; any name can be used.
- It is useful when the number of inputs is not fixed.


# Question 5. What will be the output of the following code?


In [5]:
x = 10

def test():
    x = 5
    return x

print(test(), x)


5 10


# Explanation

There are two variables named x:

1️⃣ Global variable → x = 10  
2️⃣ Local variable inside function → x = 5  

When test() is called:
- It returns the local value of x, which is 5.

Outside the function:
- The global x remains unchanged (10).

So both values are printed.


# Output

5 10


# Question 6. Which keyword is used to modify a global variable inside a function?


In [6]:
x = 10

def change_value():
    global x
    x = 20

change_value()
print(x)


20


# Explanation

The keyword **global** is used to modify a global variable inside a function.

Without using the global keyword, Python treats the variable as local,
and the global variable remains unchanged.

Using global allows the function to access and update the variable
defined outside the function.


# Question 7. What is returned if a function has no return statement?


In [7]:
def my_function():
    x = 10  # no return statement

result = my_function()
print(result)


None


# Explanation

In Python, if a function does not have a return statement,
it automatically returns **None**.

None is a special value that represents the absence of a value.


# Question 8. Which statement is true about lambda functions?


In [8]:
square = lambda x: x * x
print(square(5))


25


# Explanation

Lambda functions are small anonymous functions defined using the
lambda keyword.

Key characteristics:

- They can take any number of arguments.
- They contain only a single expression.
- They do not require a function name.
- They automatically return the result of the expression.


# Question 9. What is the primary advantage of NumPy arrays over Python lists?


In [9]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr * 2)


[2 4 6]


# Explanation

NumPy arrays are more efficient than Python lists because they are optimized
for numerical computations.

Primary advantages:

- Faster computations due to vectorized operations
- Less memory usage
- Support for mathematical and statistical operations
- Ability to perform element-wise operations easily


# Question 10. What will be the output of the following NumPy code?


In [10]:
import numpy as np

a = np.array([1, 2, 3])
print(a * 2)


[2 4 6]


# Explanation

NumPy performs element-wise operations on arrays.

When the array is multiplied by 2, each element in the array
is multiplied individually.

So:
1 × 2 = 2  
2 × 2 = 4  
3 × 2 = 6


# Output

[2 4 6]


# Question 11. What does broadcasting allow in NumPy?


In [11]:
import numpy as np

a = np.array([1, 2, 3])
b = 5

print(a + b)


[6 7 8]


# Explanation

Broadcasting allows NumPy to perform element-wise operations on arrays
of different shapes.

Instead of requiring arrays to have the same size, NumPy automatically
expands the smaller array (or scalar) to match the shape of the larger array.

This makes mathematical operations more efficient and avoids the need
for explicit loops.


# Question 12. What is the shape of the array created by:

## np.zeros((3,4))


In [12]:
import numpy as np

a = np.zeros((3, 4))
print(a.shape)


(3, 4)


# Explanation

np.zeros((3,4)) creates a 2-dimensional array with:

- 3 rows
- 4 columns

The shape of an array is written as (rows, columns).


# Final Answer

(3, 4)


# Question 13. What does np.arange(0, 10, 2) return?


In [13]:
import numpy as np

arr = np.arange(0, 10, 2)
print(arr)


[0 2 4 6 8]


# Explanation

np.arange(start, stop, step) generates values starting from the
start value up to (but not including) the stop value,
with a given step size.

Here:
start = 0  
stop = 10  
step = 2  

So the values increase by 2 each time until less than 10.


# Output

[0 2 4 6 8]


# Question 14. What is the result of the following code?


In [14]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
print(a.T)


[[1 3]
 [2 4]]


# Explanation

The .T attribute returns the transpose of the array.

Transpose means rows become columns and columns become rows.

Original array:
[[1, 2],
 [3, 4]]

After transpose:
[[1, 3],
 [2, 4]]


# Output

[[1 3]
 [2 4]]


# Question 15. Which function finds the mean while ignoring NaN values in NumPy?


In [15]:
import numpy as np

arr = np.array([1, 2, np.nan, 4])

print(np.nanmean(arr))


2.3333333333333335


# Explanation

NaN (Not a Number) represents missing values.

The function **np.nanmean()** calculates the average while ignoring
NaN values in the array.

So instead of failing or returning NaN, it computes the mean
using only valid numeric values.


# Final Answer

The function that finds the mean ignoring NaN values is **np.nanmean()**.


# Question 16. What does axis = 0 represent in NumPy aggregation?


In [16]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(np.sum(a, axis=0))


[5 7 9]


# Explanation

In NumPy, axis defines the direction of the operation.

axis = 0 → Operation is performed column-wise (down the rows)

This means values in each column are aggregated together.

For the example:

Column 1 → 1 + 4 = 5  
Column 2 → 2 + 5 = 7  
Column 3 → 3 + 6 = 9


# Final Answer

axis = 0 represents column-wise aggregation (operation performed down the rows).


# Question 17. What is the output shape of the following code?

## a = np.array([1,2,3])
## a.reshape(3,1)


In [17]:
import numpy as np

a = np.array([1, 2, 3])
b = a.reshape(3, 1)

print(b.shape)


(3, 1)


# Explanation

The original array has 3 elements.

reshape(3,1) converts it into a 2D array with:
- 3 rows
- 1 column

So the shape becomes (3, 1).


# Question 18. What is the primary data structure in Pandas?


In [18]:
import pandas as pd

data = {"Name": ["A", "B", "C"], "Age": [20, 21, 22]}
df = pd.DataFrame(data)

print(df)


  Name  Age
0    A   20
1    B   21
2    C   22


# Explanation

Pandas mainly uses two data structures:

1️⃣ Series → One-dimensional labeled array  
2️⃣ DataFrame → Two-dimensional tabular structure

Among these, the primary and most commonly used data structure is the **DataFrame**,
as it stores data in rows and columns similar to a table.


# Final Answer

The primary data structure in Pandas is the **DataFrame**.


# Question 19. What does df.head(3) return?


In [19]:
import pandas as pd

data = {"Name": ["A", "B", "C", "D", "E"], "Age": [20, 21, 22, 23, 24]}
df = pd.DataFrame(data)

df.head(3)


Name  Age
0    A   20
1    B   21
2    C   22

# Explanation

The head() function returns the first n rows of a DataFrame.

When we write df.head(3), it returns the first 3 rows from the dataset.

This is commonly used to quickly preview the data.


# Final Answer

df.head(3) returns the first 3 rows of the DataFrame.


# Question 20. How are missing values represented in Pandas?


In [20]:
import pandas as pd
import numpy as np

data = {"A": [1, 2, np.nan, 4]}
df = pd.DataFrame(data)

print(df)


     A
0  1.0
1  2.0
2  NaN
3  4.0


# Explanation

In Pandas, missing values are typically represented as **NaN**
(Not a Number), which comes from the NumPy library.

NaN is used to indicate the absence of a value in numerical columns.
In some cases, None may also appear in object-type columns,
but NaN is the standard representation.


# Final Answer

Missing values in Pandas are represented using **NaN (Not a Number)**.


# Question 21. What does df.isnull().sum() provide?


In [21]:
import pandas as pd
import numpy as np

data = {"A": [1, np.nan, 3], "B": [np.nan, 5, 6]}
df = pd.DataFrame(data)

df.isnull().sum()


A    1
B    1
dtype: int64

# Explanation

df.isnull() creates a DataFrame of boolean values where:

- True → missing value
- False → not missing

Applying .sum() counts the number of True values column-wise,
which gives the total missing values in each column.


# Final Answer

df.isnull().sum() provides the count of missing values in each column of the DataFrame.


# Question 22. What is the output of the following filtering operation?

## df[df["age"] > 25]


In [22]:
import pandas as pd

data = {"name": ["A", "B", "C", "D"], "age": [22, 28, 30, 24]}
df = pd.DataFrame(data)

df[df["age"] > 25]


name  age
1    B   28
2    C   30

# Explanation

This is a boolean filtering operation.

df["age"] > 25 creates a condition that checks each row.
Only rows where the age value is greater than 25 are selected.

So the result is a new DataFrame containing only those rows
that satisfy the condition.


# Final Answer

It returns a filtered DataFrame containing only the rows where the age is greater than 25.


# Question 23. What does groupby() primarily perform?


In [23]:
import pandas as pd

data = {"Department": ["IT", "HR", "IT", "HR"],
        "Salary": [50000, 40000, 60000, 45000]}

df = pd.DataFrame(data)

df.groupby("Department")["Salary"].mean()


Department
HR    42500.0
IT    55000.0
Name: Salary, dtype: float64

# Explanation

The groupby() function is used to group data based on one or more columns.

After grouping, we typically perform an aggregation operation such as:
- sum
- mean
- count
- max / min

It helps summarize data by categories.


# Final Answer

groupby() primarily performs aggregation based on categories by grouping
rows with similar values.


# Question 24. What is the default join type in pd.merge()?


In [24]:
import pandas as pd

df1 = pd.DataFrame({"id": [1, 2, 3], "name": ["A", "B", "C"]})
df2 = pd.DataFrame({"id": [2, 3, 4], "age": [20, 21, 22]})

pd.merge(df1, df2, on="id")


id name  age
0   2    B   20
1   3    C   21

# Explanation

When no join type is specified in pd.merge(),
Pandas performs an **inner join** by default.

This means only the rows with matching values in both DataFrames
are included in the result.


# Final Answer

The default join type in pd.merge() is **Inner Join**.


# Question 25. What does df.loc[0] access?


In [25]:
import pandas as pd

data = {"Name": ["A", "B", "C"], "Age": [20, 21, 22]}
df = pd.DataFrame(data)

df.loc[0]


Name     A
Age     20
Name: 0, dtype: object

# Explanation

The .loc[] indexer is used for label-based indexing in Pandas.

df.loc[0] accesses the row with index label 0.

It returns the entire row as a Series, including values
from all columns for that index.


# Final Answer

df.loc[0] accesses the row with index label 0 and returns it as a Series.
